name:                Public-Holidays-of-the-World
version:             0.1.0.0
github:              "githubuser/Public-Holidays-of-the-World"
license:             BSD3
author:              "Franklin Antony"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Public-Holidays-of-the-World#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- bytestring
- aeson
- HDBC
- HDBC-sqlite3

library:
  source-dirs: src

executables:
  Public-Holidays-of-the-World-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Public-Holidays-of-the-World

build:
  haddock-arguments:
    haddock-args:
    - "--odir=./docs"    

tests:
  Public-Holidays-of-the-World-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Public-Holidays-of-the-World
